/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AnswerPanel: typeof import('./src/components/Surveys/AnswerPanel.vue')['default']
    AnswerRating: typeof import('./src/components/forms/AnswerRating.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EnrollmentQuestions: typeof import('./src/components/Surveys/EnrollmentQuestions.vue')['default']
    EnrollmentResponse: typeof import('./src/components/Surveys/Responses/EnrollmentResponse.vue')['default']
    EnrollUser: typeof import('./src/components/EnrollUser.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ParameteredQuery: typeof import('./src/components/Surveys/ParameteredQuery.vue')['default']
    ParameterizedQuery: typeof import('./src/components/Surveys/ParameterizedQuery.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    QuestionPanel: typeof import('./src/components/Surveys/QuestionPanel.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Slider: typeof import('primevue/slider')['default']
    SurveyDetails: typeof import('./src/components/Surveys/SurveyDetails.vue')['default']
    SurveyImage: typeof import('./src/components/Surveys/SurveyImage.vue')['default']
    SurveyList: typeof import('./src/components/SurveyList.vue')['default']
    SurveyQuery: typeof import('./src/components/Surveys/SurveyQuery.vue')['default']
    SurveyResponse: typeof import('./src/components/Surveys/Responses/SurveyResponse.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TimeFramePicker: typeof import('./src/components/forms/TimeFramePicker.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
