services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    #depends_on:
    #  - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    #command: tail -f /dev/null

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot:/app
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/init-scripts:/docker-entrypoint-initdb.d:ro

volumes:
  mongo-data:
